package Pong;

/**
* Pong/ServidorPongHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/EHECA/Desktop/PONG.idl
* domingo 25 de junio de 2017 02:11:41 AM CDT
*/

public final class ServidorPongHolder implements org.omg.CORBA.portable.Streamable
{
  public Pong.ServidorPong value = null;

  public ServidorPongHolder ()
  {
  }

  public ServidorPongHolder (Pong.ServidorPong initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Pong.ServidorPongHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Pong.ServidorPongHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Pong.ServidorPongHelper.type ();
  }

}
